### ISSUE TITLE
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/snuffleupagus.so'

### ISSUE THREAD

**Issue by garyrozanc** [Dukecitysolutions/sentora-php7-upgrade#1]
Running the bash script on Centos 7 give the following error: PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/snuffleupagus.so'

This is resulting in PHP 5.4.16 not being updated.

**Comment by Dukecitysolutions** [comment]
After talking to garyrozanc. He ran “yum install epel-release” after Sentora clean install causing php7_upgrader to not install php 7.3. Causing snuffleupagus to not compile correctly and share .so file. I will look into this issue.

**Comment by Dukecitysolutions** [comment]
Closing this issue as it was a special case and shouldnt case any other issues

**Comment by Dukecitysolutions** [comment]
Is any else getting this error on first time install/upgrade to PHP 7???

`PHP Warning: PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/snuffleupagus.so'`

causing installer/upgrader script to not finish install or start apache???
