### ISSUE TITLE
daemon.php broken by snuffleupagus

### ISSUE THREAD

**Issue by VedranIteh** [Dukecitysolutions/sentora-php7-upgrade#2]
PHP Fatal error:  [snuffleupagus][0.0.0.0][disabled_function] Aborted execution on call of the function 'escapeshellcmd' in /etc/sentora/panel/dryden/ctrl/system.class.php on line 27

Fatal error: [snuffleupagus][0.0.0.0][disabled_function] Aborted execution on call of the function 'escapeshellcmd' in /etc/sentora/panel/dryden/ctrl/system.class.php on line 27

**Comment by Dukecitysolutions** [comment]
Vedranlteh,
This issue has already been resolved in v1.0.3.1-Build-0.3.3 - BETA.
Please run-
`bash <(curl -L -Ss http://zppy-repo.dukecitysolutions.com/repo/sentora-live/php7_upgrade/update.sh)`

New way to run cron manually run-
`php -d "sp.configuration_file=/etc/sentora/configs/php/sp/sentora.rules" -q /etc/sentora/panel/bin/daemon.php`

You can check your v1.0.3.1 version/build in control panel under ADMIN->UPDATES
I try to update code daily for fixes when found. Please update and confirm issues are fixed. Thank you for your help

**Comment by VedranIteh** [comment]
it acctually broke after the latest update on 0.3.3 :\

**Comment by Dukecitysolutions** [comment]
Vedranlteh,
This issue has already been resolved in v1.0.3.1-Build-0.3.3 - BETA.
Please run-
`bash <(curl -L -Ss http://zppy-repo.dukecitysolutions.com/repo/sentora-live/php7_upgrade/update.sh)`

New way to run cron manually run-
`php -d "sp.configuration_file=/etc/sentora/configs/php/sp/sentora.rules" -q /etc/sentora/panel/bin/daemon.php`

You can check your v1.0.3.1 version/build in control panel under ADMIN->UPDATES
I try to update code daily for fixes when found. Please update and confirm issues are fixed. Thank you for your help

**Comment by Dukecitysolutions** [comment]
> it acctually broke after the latest update on 0.3.3 :\

What OS are you running this on? You can reach me directly on skype bombisallthat@yahoo.com
for direct quick help.

**Comment by VedranIteh** [comment]
CentOS 6, Can't skype right now, it's not urgent at all.

What file, method, code was updated to repair this ? I can check if everything updated alright by the script.

Thank you, great work

**Comment by Dukecitysolutions** [comment]
Replace zdaemon - /etc/cron.d/zdaemon with attached file. 

Then run -
`php -d "sp.configuration_file=/etc/sentora/configs/php/sp/sentora.rules" -q /etc/sentora/panel/bin/daemon.php`

This is included in update.sh I sent earlier. Ive tested it on all support OS with no issues.

[zdaemon.zip](https://github.com/Dukecitysolutions/sentora-php7-upgrade/files/4049782/zdaemon.zip)

**Comment by Dukecitysolutions** [comment]
Wait I see an issue. Please standby for a fix in installer/updater

**Comment by VedranIteh** [comment]
solved, thanks

**Comment by VedranIteh** [comment]
th error was in my cron.d/zdaemon line

**Comment by Dukecitysolutions** [comment]
> th error was in my cron.d/zdaemon line

Please explain error...

**Comment by VedranIteh** [comment]
it wasn't updated to run with -d flag and snuffleupagus ruleset for some reason it was still as before.
