### ISSUE TITLE
cURL site verification issue

### ISSUE THREAD

**Issue by TomislavBombas** [Dukecitysolutions/sentora-php7-upgrade#3]
When first opening a site it "breaks".
The issue is, in: /wp-includes/Requests/Transport/cURL.php on line 150 ( curl_setopt($this->handle, CURLOPT_SSL_VERIFYHOST, 0); ).
Simply commenting that line makes the issue go away, as a quick fix.
The issue is with snuffleupagus.

EDIT/ It was late so i did not read through. This is not an issue with snuffleupagus. just changed curl options and all is good. it was my mistake

**Comment by Dukecitysolutions** [comment]
In build-0.3.4 I commended curl_opt out temporary tell I could fix properly. Could you share what curl settings you changed? Thank you for testing.

**Comment by TomislavBombas** [comment]
The issue is in php.ini. SSL certificate was not properly set to be verified. That is what the error was. Curl was set to ignore verification and it produced an error. As a quick fix i changed the cURL.php file and set lines 150, 151 and 159 option to 1, like this: curl_setopt($this->handle, CURLOPT_SSL_VERIFYHOST, 1);
I will change the php.ini settings tomorrow and post the solution here for people with same issue. After that i will return original cURL.php

**Comment by Dukecitysolutions** [comment]
> The issue is in php.ini. SSL certificate was not properly set to be verified. That is what the error was. Curl was set to ignore verification and it produced an error. As a quick fix i changed the cURL.php file and set lines 150, 151 and 159 option to 1, like this: curl_setopt($this->handle, CURLOPT_SSL_VERIFYHOST, 1);
> I will change the php.ini settings tomorrow and post the solution here for people with same issue. After that i will return original cURL.php

What OS are you using? Ubuntu 16?

**Comment by TomislavBombas** [comment]
CentOS 7. I did not set up server so i am not sure about details, versuon, etc. Should i provide it in reply? Wasn't planing since it is the php.ini...

**Comment by Dukecitysolutions** [comment]
Just needed the OS. Thank you. It helps me track issues.

**Comment by Dukecitysolutions** [comment]
@TomislavBombas ,
Did you ever resolve this issue? If so what is the fix you used? Thank you for your help.
