### ISSUE TITLE
centos 6 user domains not working (Redirect to panel)

### ISSUE THREAD

**Issue by andykimpe** [Dukecitysolutions/sentora-php7-upgrade#4]
centos 6 domain not work

all domain redirect to panel page

pleases write Snuffleupagus config online on http-vhost.conf

centos 6 use apache 2.2 and no 2.4

configuration and probably different

**Comment by Dukecitysolutions** [comment]
What build version are you using??? Go to ADMIN->UPDATES in panel.

**Comment by andykimpe** [comment]
I will not say I went to 7

but it was under openvz with the centos-6-minimal template

and activate deposits were

base
epel
remi
remi-safe
remi-php73

after enable remi repo

I execut

bash <(curl -L -Ss http://zppy-repo.dukecitysolutions.com/repo/sentora-live/php7_upgrade/install.sh)

bash <(curl -L -Ss http://zppy-repo.dukecitysolutions.com/repo/sentora-live/php7_upgrade/update.sh)

on the other hand I have found in your Snuffleupagus config you place the rules file directly in the php config of this made if you want to disable it for a domain it remains active

and you are too restrictive on your config

seriously i'm ending up with her

Required function curl_init is not available

deactivate curl there is no interest

reset the same config as with suhosin

instead of blocking functions that weren't

php_admin_value suhosin.executor.func.blacklist "passthru, show_source, shell_exec, system, pcntl_exec, popen, pclose, proc_open, proc_nice, proc_terminate, proc_get_status, proc_close, leak, apache_child_terminate, posix_kill, posix_mkfifo, posix_setpgid, posix_setsid, posix_setuid, escapeshellcmd, escapeshellarg, exec"

there and where curl in nowhere

I will see to make you a comit

**Comment by Dukecitysolutions** [comment]
Again I will ask WHAT BUILD ARE YOU ON????? Login to your panel. GO TO ADMIN->UPDATES in the panel.

Please post your Sentora build version.

As for the original issue you posted about `centos 6 domain not work` build 0.3.5-BETA should resolve CentOS 6 domain redirected to panel. I forgot to add `NameVirtualHost` for apache 2.2. If not please contact me through skype @bombisallthat@yahoo.com so I can help you address issues without flooding Github issues for no reason.

As for other stuff like Snuffleupagus rules. I am experimenting with different ways to secure the system. Snuffleupagus DEFAULT rules are very aggressive. I'm trying to simplify the config of individual VHOSTS with applying all default RULES in Snuffleupagus.rules to VHOSTS in addition VHOST independent rules to protect against misconfigurations by users trying to delete domain VHOST snuff rules like you tried doing. It a FAIL-SAFE.

Currently, my Sentora live-build 0.3.5-BETA does not support Disabling Snuff rules. This is a FAIL-SAFE. If you try to disable VHOST snuff rules. Snuffleupagus will only lock your VHOST up even more.
You have to add (ALLOW) rules to individual VHOSTS.

Yes, I will admit DEFAULT rules are very tight and need some work. If you need help adjusting snuff rules contact me. DO NOT OPEN A ISSUE.
