### ISSUE TITLE
Error with Panel Login

### ISSUE THREAD

**Issue by digifelis** [Dukecitysolutions/sentora-php7-upgrade#6]
I cannot log in to the panel after the update. If I try to login incorrectly, it's okay. but I'm trying to login with the correct password, I got 500 errors.

Operating System: Ubuntu 16.04.6 LTS
Php : 7.3

**Comment by Dukecitysolutions** [comment]
Hi, There was a bug in the update script. It was fixed late last night. Please run

`bash <(curl -L -Ss http://zppy-repo.dukecitysolutions.com/repo/sentora-live/php7_upgrade/update.sh)`

This should fix your issue. Please let me know if you have any issues.

**Comment by digifelis** [comment]
ı tried your solution but it has not worked for me.
right now ı examined log files which placed under /var/log and /var/sentora/logs/ . but there isn't any log line about this problem. do you have any advice?

**Comment by Dukecitysolutions** [comment]
Please send/attach me your update log with recent date in root folder. (DATE)sentora_php7_update.log

**Comment by digifelis** [comment]
[2020-01-26_22.12.32_sentora_php7_update.log](https://github.com/Dukecitysolutions/sentora-php7-upgrade/files/4115899/2020-01-26_22.12.32_sentora_php7_update.log)

**Comment by Dukecitysolutions** [comment]
Digifelis,
Looking at log you sent. I can see that PHP 7.4 got installed. This might be causing the issue. I need you to run a series of commands to check and repair.

Do you have a skype account? I can help you quicker thru there. I will post fix here for everyone after.

**Comment by digifelis** [comment]
okay. my skype id is bes-tas
my email is mansur@siirt.edu.tr . we can arrange skype appoint. 
let me know when we can examine on server by UTC time.
kind regards

**Comment by digifelis** [comment]
hi, 
ı solved my problem.
 ı removed all php service with sudo apt-get purge php7.0-common command. 
then ı run install.sh script. now panel is openning. 
but ı have some problem with DNS services.

**Comment by Dukecitysolutions** [comment]
I checked updater with many installs can’t reproduce. That does not mean there is not a issue. I will add code to help Ubuntu PHP 7.3 default and not install/activate other PHP 7 versions
