### ISSUE TITLE
Install shell script not available

### ISSUE THREAD

**Issue by digifelis** [Dukecitysolutions/sentora-php7-upgrade#7]
I can't run the install script . 

Repo *sentora_php7_upgrade.sh* is not available at this moment. This may be caused by Admin making new installers. Please check back later. Exiting installer. Please contact script admin

**Comment by Dukecitysolutions** [comment]
I’m currently running a test due to reported issues. Installer/updater scripts will be online in a few minutes. All seems well. Let me know if you have any trouble.
