### ISSUE TITLE
DNS services

### ISSUE THREAD

**Issue by digifelis** [Dukecitysolutions/sentora-php7-upgrade#8]
After update, sentora DNS services aren't working. in fact, ı have checked service on sentora panel and it is working. then ı have checked the listening port and it is OK. 
problem isn't from apache. 

Operating System: Ubuntu 16.04.6 LTS
Php : 7.3

**Comment by Dukecitysolutions** [comment]
Thank you for opening a new ticket for this. I am looking into this as we speak.

**Comment by Dukecitysolutions** [comment]
Digifeilis,
I found issue with Bind in Ubuntu 16 setup. Appmor was configured wrong & bind managed-keys. Steps below to fix by hand-

`git clone https://github.com/Dukecitysolutions/sentora-php7-upgrade sentora_php7_upgrade`


`rm -rf /etc/apparmor.d/usr.sbin.named`

`cp -r  ~/sentora_php7_upgrade/preconf/apparmor.d/usr.sbin.named /etc/apparmor.d/`

`
sed -i '\~dnssec-lookaside auto;~a   managed-keys-directory "/var/named/dynamic";' /etc/bind/named.conf
` - ONE LINE

`rm -rf /var/named/dynamic/managed-keys.bind`

`systemctl restart bind9`

and reboot system

or 

`bash <(curl -L -Ss http://zppy-repo.dukecitysolutions.com/repo/sentora-live/php7_upgrade/update.sh)`

That should fix it!!!

**Comment by digifelis** [comment]
hi,
I ran update.sh and it was worked for me.
thanks.

**Comment by Dukecitysolutions** [comment]
Your very welcome. Thank you for your help testing.
